name: Build-Prerelease
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 5'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]')
      }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
        id: repository
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Builder
        shell: bash
        run: |
          export CI_PROJECT_DIR=${PWD}
          export CI_REGISTRY_IMAGE=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}
          export BUILDX_PLATFORM=linux/amd64,linux/arm64
          export CADVISOR_VERSION=$(curl -s https://api.github.com/repos/google/cadvisor/releases | jq -r "[[.[] | select(.draft != true) | select(.prerelease == true)][0]][0].name")
          export GO111MODULE=on
          export GO_FLAGS="-tags=netgo"
          export CGO_ENABLED="1"
          export OUTPUT_NAME_WITH_ARCH=false
          echo ${CI_REGISTRY_IMAGE}
          echo ${BUILDX_PLATFORM}
          echo ${CADVISOR_VERSION}
          echo #0
          docker buildx build --platform=${BUILDX_PLATFORM} --cache-from ${CI_REGISTRY_IMAGE}/cache/builder --cache-to ${CI_REGISTRY_IMAGE}/cache/builder --build-arg CADVISOR_VERSION -f Dockerfile.builder -t ${CI_REGISTRY_IMAGE}/builder --push "."
          echo #1
          git clone https://github.com/google/cadvisor
          cd cadvisor
          git checkout master
          go mod download
          ./build/assets.sh
          go get github.com/IBM/sarama@latest
          go mod tidy
          go mod download
          go mod vendor
          cd cmd
          go get github.com/IBM/sarama@latest
          go mod tidy
          go mod download
          go mod vendor
          cd ..
          echo step build
          cat go.mod
          mkdir -p amd64
          GOOS=linux GOARCH=amd64 ./build/build.sh amd64
          mv _output/cadvisor amd64/
          mkdir -p arm64
          sudo apu update -y 
          sudo apt install gcc-aarch64-linux-gnu -y
          GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc ./build/build.sh arm64
          mv _output/cadvisor arm64/
          go mod vendor
          rm -f cadvisor || true
          cd ..
          tar czf cadvisor.tar.gz cadvisor
          cd $(go env GOMODCACHE)/..
          tar czf ${CI_PROJECT_DIR}/mod.tar.gz mod
          cd -
          echo #2
          docker buildx build --platform=${BUILDX_PLATFORM} --cache-from ${CI_REGISTRY_IMAGE}/cache/cadvisor:${CADVISOR_VERSION}-pre --cache-to ${CI_REGISTRY_IMAGE}/cache/cadvisor:${CADVISOR_VERSION}-pre --build-arg CADVISOR_VERSION -f Dockerfile.deploy -t ${CI_REGISTRY_IMAGE}/cadvisor:${CADVISOR_VERSION}-pre -t ${CI_REGISTRY_IMAGE}/cadvisor:latest-pre --push "."
          skopeo copy --all --dest-creds=zcube:${{ secrets.DOCKER_HUB_KEY }} docker://${CI_REGISTRY_IMAGE}/cadvisor:${CADVISOR_VERSION}-pre docker://zcube/cadvisor:${CADVISOR_VERSION}-pre
          skopeo copy --all --dest-creds=zcube:${{ secrets.DOCKER_HUB_KEY }} docker://${CI_REGISTRY_IMAGE}/cadvisor:${CADVISOR_VERSION}-pre docker://zcube/cadvisor:latest-pre
